### ISSUE TITLE
Erro with Registering and error when importing database

### ISSUE THREAD

**Issue by Nanzige** [rushabh-wadkar/iBank#1]
Hi , thanks for developing the project however, am registering below problems. please assist andalso, thanks to assist with login detail

Invalid default value for "doj"

**Comment by rushabh-wadkar** [comment]
Looking at the image you sent looks like you should update your xampp [Download Link](https://www.apachefriends.org/download.html) with 
**PHP version >= 5.6**
It either might be because of the xampp problem or lesser PHP version problem.

Once you update,

> Just goto localhost/phpmyadmin, create a database named `ibank` and then click import after selecting database i.e ibank. In the import section, browse for ibank.sql in the `SourceCode/Database` from the repository which you downloaded. Then, click OK.

**It must work.**

Regarding the login process, each user password is MD5 encrypted, so just make sure you delete all the data/entries from each table `customers, transaction_transfer, transaction_withdraw etc. if any` and register a new user from the scratch. This will save much of your precious time. 

Hope it helps!

**Comment by Nanzige** [comment]
The sir. I will check and keep u posted.

**Comment by Nanzige** [comment]
Good Day Sir ,

Thanks a lot. It worked.


Best Regards,

NANZIGE MAHAWUYA
Tel: +256754084013
Email. nanz.maha@gmail.com
Web:  nanzigemahawuya.wordpress.com
Proffessional Network:linkedin.
<https://ug.linkedin.com/in/nanzige-mahawuya-26737073>

**Comment by rushabh-wadkar** [comment]
Yep.
Closing the issue.
